site_name: Lazarus NLP
site_url: https://lazarusnlp.github.io/
repo_url: https://github.com/lazarusnlp/lazarusnlp.github.io/
docs_dir: docs

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.sections
    - navigation.top
    # - toc.integrate

nav:
  - Home: index.md
  - Blogs:
      - Bible Alignment: blogs/bible_alignment.md
      - Indonesian Accents and Regional Languages: blogs/accents_and_languages.md
  - Projects:
      - Sentence Embeddings: projects/sentence-embeddings.md
      - Machine Translation: projects/machine-translation.md

plugins:
  - social
  - search
  - external-markdown

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
